// frontend-vue/src/components/PermissionGuard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { usePermissionStore } from '../stores/permission'

const props = defineProps<{
  roles?: string[]
  scenarioId?: string
  permission?: string
}>()

const permStore = usePermissionStore()

const allowed = computed(() => {
  if (props.roles) return permStore.hasRole(props.roles)
  if (props.scenarioId && props.permission) return permStore.hasScenarioPermission(props.scenarioId, props.permission)
  if (props.permission) return permStore.hasPermission(props.permission)
  return true
})
</script>

<template>
  <slot v-if="allowed" />
  <slot v-else name="fallback" />
</template>

// frontend/src/components/PermissionGuard.tsx
import React, { ReactNode } from 'react';
import { usePermission } from '../hooks/usePermission';

interface PermissionGuardProps {
  roles?: string[];
  scenarioId?: string;
  permission?: string;
  fallback?: ReactNode;
  children: ReactNode;
}

export const PermissionGuard: React.FC<PermissionGuardProps> = ({
  roles,
  scenarioId,
  permission,
  fallback = null,
  children,
}) => {
  const { hasRole, hasScenarioPermission } = usePermission();

  // Role check
  if (roles && !hasRole(roles)) {
    return <>{fallback}</>;
  }

  // Scenario permission check
  if (scenarioId && permission && !hasScenarioPermission(scenarioId, permission)) {
    return <>{fallback}</>;
  }

  return <>{children}</>;
};
