// frontend/src/components/ScenarioKeywordsTab.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, Select, Switch, Space, message, Popconfirm, Tag, Radio, Row, Col } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { useSearchParams } from 'react-router-dom';
import { ScenarioKeyword, MetaTag } from '../types';
import { scenarioKeywordsApi, metaTagsApi, getErrorMessage } from '../api';

const { Option } = Select;
const { Search } = Input;

interface ScenarioKeywordsTabProps {
  scenarioId: string;
  mode: 'custom' | 'super';
}

const ScenarioKeywordsTab: React.FC<ScenarioKeywordsTabProps> = ({ scenarioId, mode }) => {
  const [searchParams] = useSearchParams();
  const [keywords, setKeywords] = useState<ScenarioKeyword[]>([]);
  const [filteredKeywords, setFilteredKeywords] = useState<ScenarioKeyword[]>([]);
  const [tags, setTags] = useState<MetaTag[]>([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [categoryFilter, setCategoryFilter] = useState<'all' | 0 | 1>('all');
  const [searchText, setSearchText] = useState<string>('');
  const [hasAccess, setHasAccess] = useState<boolean>(true);
  const [form] = Form.useForm();

  const ruleMode = mode === 'custom' ? 1 : 0;

  useEffect(() => {
    const cat = searchParams.get('category');
    if (cat === '0') setCategoryFilter(0);
    else if (cat === '1') setCategoryFilter(1);
    else if (!cat) setCategoryFilter('all');
  }, [searchParams]);

  useEffect(() => {
    fetchKeywords();
    fetchTags();
  }, [scenarioId, mode]);

  useEffect(() => {
    applyFilters();
  }, [keywords, categoryFilter, searchText]);

  const fetchKeywords = async () => {
    if (!scenarioId) return;
    setLoading(true);
    try {
      const res = await scenarioKeywordsApi.getByScenario(scenarioId, ruleMode);
      setKeywords(res.data);
      setHasAccess(true);
    } catch (error: any) {
      if (error.response?.status === 403) {
        setHasAccess(false);
      }
      message.error(getErrorMessage(error, '获取场景敏感词失败'));
    } finally {
      setLoading(false);
    }
  };

  const fetchTags = async () => {
    try {
      const res = await metaTagsApi.getAll();
      setTags(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取标签列表失败'));
    }
  };

  const applyFilters = () => {
    let filtered = [...keywords];

    // Filter by category
    if (categoryFilter !== 'all') {
      filtered = filtered.filter(k => k.category === categoryFilter);
    }

    // Filter by search text
    if (searchText.trim()) {
      const searchLower = searchText.toLowerCase();
      filtered = filtered.filter(k => k.keyword.toLowerCase().includes(searchLower));
    }

    setFilteredKeywords(filtered);
  };

  const handleAdd = () => {
    setEditingId(null);
    form.resetFields();
    form.setFieldsValue({
      scenario_id: scenarioId,
      is_active: true,
      category: 1, // Default to blacklist
      rule_mode: ruleMode,
      risk_level: 'High'
    });
    setIsModalOpen(true);
  };

  const handleEdit = (record: ScenarioKeyword) => {
    setEditingId(record.id);
    form.setFieldsValue(record);
    setIsModalOpen(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await scenarioKeywordsApi.delete(id);
      message.success('敏感词已删除');
      fetchKeywords();
    } catch (error: any) {
      message.error(getErrorMessage(error, '删除失败'));
    }
  };

  const handleOk = async () => {
    try {
      const values = await form.validateFields();
      if (editingId) {
        await scenarioKeywordsApi.update(editingId, values);
        message.success('敏感词已更新');
      } else {
        await scenarioKeywordsApi.create(values);
        message.success('敏感词已成功添加');
      }
      setIsModalOpen(false);
      fetchKeywords();
    } catch (error: any) {
      console.error(error);
      if (error.errorFields) {
        // Form validation error, do nothing
      } else {
        message.error(getErrorMessage(error, '操作失败'));
      }
    }
  };

  const columns = [
    {
      title: '敏感词内容',
      dataIndex: 'keyword',
      key: 'keyword',
      width: 200,
    },
    {
      title: '名单类型',
      dataIndex: 'category',
      key: 'category',
      width: 120,
      render: (val: number) => val === 0 ? <Tag color="green">白名单</Tag> : <Tag color="red">黑名单</Tag>
    },
    {
      title: '关联标签',
      dataIndex: 'tag_code',
      key: 'tag_code',
      width: 150,
      render: (text: string) => text ? <Tag color="blue">{text}</Tag> : '-'
    },
    {
      title: '风险等级',
      dataIndex: 'risk_level',
      key: 'risk_level',
      width: 120,
      render: (level: string) => {
        let color = 'default';
        if (level === 'High') color = 'red';
        if (level === 'Medium') color = 'orange';
        if (level === 'Low') color = 'green';
        return level ? <Tag color={color}>{level}</Tag> : '-';
      }
    },
    {
      title: '是否启用',
      dataIndex: 'is_active',
      key: 'is_active',
      width: 100,
      render: (active: boolean) => <Switch size="small" checked={active} disabled />
    },
    {
      title: '操作',
      key: 'action',
      width: 150,
      render: (_: any, record: ScenarioKeyword) => hasAccess ? (
        <Space size="middle">
          <Button icon={<EditOutlined />} onClick={() => handleEdit(record)} size="small" />
          <Popconfirm title="确定要删除吗？" onConfirm={() => handleDelete(record.id)} okText="确定" cancelText="取消">
            <Button icon={<DeleteOutlined />} danger size="small" />
          </Popconfirm>
        </Space>
      ) : <Tag color="default">无权限</Tag>,
    },
  ];

  return (
    <div>
      <Row gutter={16} style={{ marginBottom: 16 }} align="middle">
        <Col flex="auto">
          <Space>
            <span>过滤:</span>
            <Radio.Group value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}>
              <Radio.Button value="all">全部</Radio.Button>
              <Radio.Button value={1}>仅黑名单</Radio.Button>
              <Radio.Button value={0}>仅白名单</Radio.Button>
            </Radio.Group>
          </Space>
        </Col>
        <Col>
          <Search
            placeholder="搜索敏感词"
            allowClear
            style={{ width: 250 }}
            value={searchText}
            onChange={e => setSearchText(e.target.value)}
          />
        </Col>
        <Col>
          {hasAccess && (
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
              添加敏感词
            </Button>
          )}
        </Col>
      </Row>

      <Table
        columns={columns}
        dataSource={filteredKeywords}
        rowKey="id"
        loading={loading}
        pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (total) => `共 ${total} 条` }}
      />

      <Modal
        title={editingId ? "编辑敏感词" : "添加敏感词"}
        open={isModalOpen}
        onOk={handleOk}
        onCancel={() => setIsModalOpen(false)}
        okText="确定"
        cancelText="取消"
        width={600}
      >
        <Form form={form} layout="vertical">
          <Form.Item name="scenario_id" label="场景 ID" rules={[{ required: true }]}>
            <Input disabled />
          </Form.Item>
          <Form.Item name="rule_mode" hidden>
            <Input />
          </Form.Item>
          <Form.Item name="keyword" label="敏感词内容" rules={[{ required: true, message: '请输入敏感词' }]}>
            <Input placeholder="例如：某些敏感词汇" />
          </Form.Item>
          <Form.Item name="category" label="名单类型" rules={[{ required: true }]}>
            <Select>
              <Select.Option value={1}>黑名单 (Block)</Select.Option>
              <Select.Option value={0}>白名单 (Allow)</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item 
            name="tag_code" 
            label="关联标签 (Tag Code)"
            rules={[{ required: true, message: '必须选择标签' }]}
          >
            <Select placeholder="请选择标签" showSearch optionFilterProp="children" allowClear>
              {tags.map(tag => (
                <Option key={tag.tag_code} value={tag.tag_code}>{tag.tag_name} ({tag.tag_code})</Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item name="risk_level" label="风险等级">
            <Select placeholder="选择风险等级">
              <Select.Option value="High">高 (High)</Select.Option>
              <Select.Option value="Medium">中 (Medium)</Select.Option>
              <Select.Option value="Low">低 (Low)</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="is_active" label="是否启用" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default ScenarioKeywordsTab;

// frontend-vue/src/components/ScenarioKeywordsTab.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { ElMessage } from 'element-plus'
import type { ScenarioKeyword, MetaTag } from '../types'
import { scenarioKeywordsApi, metaTagsApi, getErrorMessage } from '../api'

const props = defineProps<{ scenarioId: string; mode: 'custom' | 'super' }>()
const ruleMode = computed(() => props.mode === 'custom' ? 1 : 0)

const keywords = ref<ScenarioKeyword[]>([])
const filteredKeywords = ref<ScenarioKeyword[]>([])
const tags = ref<MetaTag[]>([])
const loading = ref(false)
const dialogVisible = ref(false)
const editingId = ref<string | null>(null)
const categoryFilter = ref<'all' | 0 | 1>('all')
const searchText = ref('')
const hasAccess = ref(true)
const form = ref<Partial<ScenarioKeyword>>({})

watch([() => props.scenarioId, () => props.mode], () => { fetchKeywords(); fetchTags() }, { immediate: true })
watch([keywords, categoryFilter, searchText], applyFilters)

async function fetchKeywords() {
  if (!props.scenarioId) return
  loading.value = true
  try { keywords.value = (await scenarioKeywordsApi.getByScenario(props.scenarioId, ruleMode.value)).data; hasAccess.value = true }
  catch (e: any) { if (e.response?.status === 403) hasAccess.value = false; ElMessage.error(getErrorMessage(e, '获取场景敏感词失败')) }
  finally { loading.value = false }
}

async function fetchTags() {
  try { tags.value = (await metaTagsApi.getAll()).data } catch {}
}

function applyFilters() {
  let filtered = [...keywords.value]
  if (categoryFilter.value !== 'all') filtered = filtered.filter(k => k.category === categoryFilter.value)
  if (searchText.value.trim()) { const s = searchText.value.toLowerCase(); filtered = filtered.filter(k => k.keyword.toLowerCase().includes(s)) }
  filteredKeywords.value = filtered
}

function handleAdd() {
  editingId.value = null
  form.value = { scenario_id: props.scenarioId, is_active: true, category: 1, rule_mode: ruleMode.value, risk_level: 'High', keyword: '', tag_code: '' }
  dialogVisible.value = true
}
function handleEdit(row: ScenarioKeyword) { editingId.value = row.id; form.value = { ...row }; dialogVisible.value = true }
async function handleDelete(row: ScenarioKeyword) {
  try { await scenarioKeywordsApi.delete(row.id); ElMessage.success('已删除'); fetchKeywords() }
  catch (e: any) { ElMessage.error(getErrorMessage(e, '删除失败')) }
}
async function handleSubmit() {
  try {
    if (editingId.value) { await scenarioKeywordsApi.update(editingId.value, form.value); ElMessage.success('已更新') }
    else { await scenarioKeywordsApi.create(form.value as Omit<ScenarioKeyword, 'id'>); ElMessage.success('已添加') }
    dialogVisible.value = false; fetchKeywords()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '操作失败')) }
}

function getRiskColor(level: string) { return level === 'High' ? 'danger' : level === 'Medium' ? 'warning' : 'success' }
</script>

<template>
  <div>
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
      <div style="display:flex;gap:8px;align-items:center">
        <span>过滤:</span>
        <el-radio-group v-model="categoryFilter" size="small">
          <el-radio-button label="all">全部</el-radio-button>
          <el-radio-button :label="1">仅黑名单</el-radio-button>
          <el-radio-button :label="0">仅白名单</el-radio-button>
        </el-radio-group>
      </div>
      <div style="display:flex;gap:8px">
        <el-input v-model="searchText" placeholder="搜索敏感词" clearable style="width:200px" />
        <el-button v-if="hasAccess" type="primary" @click="handleAdd">添加敏感词</el-button>
      </div>
    </div>
    <el-table :data="filteredKeywords" v-loading="loading" border>
      <el-table-column prop="keyword" label="敏感词内容" min-width="200" />
      <el-table-column prop="category" label="名单类型" width="120">
        <template #default="{ row }">
          <el-tag :type="row.category === 0 ? 'success' : 'danger'">{{ row.category === 0 ? '白名单' : '黑名单' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="tag_code" label="关联标签" width="150">
        <template #default="{ row }"><el-tag v-if="row.tag_code">{{ row.tag_code }}</el-tag><span v-else>-</span></template>
      </el-table-column>
      <el-table-column prop="risk_level" label="风险等级" width="120">
        <template #default="{ row }">
          <el-tag v-if="row.risk_level" :type="getRiskColor(row.risk_level)">{{ row.risk_level }}</el-tag><span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column prop="is_active" label="状态" width="80">
        <template #default="{ row }"><el-switch :model-value="row.is_active" disabled size="small" /></template>
      </el-table-column>
      <el-table-column label="操作" width="140" fixed="right">
        <template #default="{ row }">
          <template v-if="hasAccess">
            <el-button size="small" @click="handleEdit(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="handleDelete(row)">删除</el-button>
          </template>
          <el-tag v-else type="info">无权限</el-tag>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog :title="editingId ? '编辑敏感词' : '添加敏感词'" v-model="dialogVisible" width="550px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="场景 ID"><el-input :model-value="form.scenario_id" disabled /></el-form-item>
        <el-form-item label="敏感词" required><el-input v-model="form.keyword" placeholder="输入敏感词" /></el-form-item>
        <el-form-item label="名单类型" required>
          <el-select v-model="form.category"><el-option :value="1" label="黑名单 (Block)" /><el-option :value="0" label="白名单 (Allow)" /></el-select>
        </el-form-item>
        <el-form-item label="关联标签" required>
          <el-select v-model="form.tag_code" filterable placeholder="选择标签">
            <el-option v-for="t in tags" :key="t.tag_code" :label="`${t.tag_name} (${t.tag_code})`" :value="t.tag_code" />
          </el-select>
        </el-form-item>
        <el-form-item label="风险等级">
          <el-select v-model="form.risk_level"><el-option value="High" label="高 (High)" /><el-option value="Medium" label="中 (Medium)" /><el-option value="Low" label="低 (Low)" /></el-select>
        </el-form-item>
        <el-form-item label="是否启用"><el-switch v-model="form.is_active" /></el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>
