// frontend-vue/src/views/AuditLogs.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { auditLogsApi, getErrorMessage } from '../api'
import type { AuditLog } from '../types'
import { ElMessage } from 'element-plus'
import dayjs from 'dayjs'

const logs = ref<AuditLog[]>([])
const loading = ref(false)
const total = ref(0)
const currentPage = ref(1)
const pageSize = ref(20)
const detailDrawerOpen = ref(false)
const selectedLog = ref<AuditLog | null>(null)

// Filter form
const filterUsername = ref('')
const filterAction = ref('')
const filterResourceType = ref('')
const filterScenarioId = ref('')
const filterDateRange = ref<[Date, Date] | null>(null)

async function fetchLogs(filters: any = {}) {
  loading.value = true
  try {
    const params: any = {
      skip: (currentPage.value - 1) * pageSize.value,
      limit: pageSize.value,
      ...filters,
    }
    const res = await auditLogsApi.queryLogs(params)
    logs.value = res.data.items || res.data
    total.value = res.data.total || res.data.length
  } catch (e: any) {
    ElMessage.error(getErrorMessage(e, '获取审计日志失败'))
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  const filters: any = {}
  if (filterUsername.value) filters.username = filterUsername.value
  if (filterAction.value) filters.action = filterAction.value
  if (filterResourceType.value) filters.resource_type = filterResourceType.value
  if (filterScenarioId.value) filters.scenario_id = filterScenarioId.value
  if (filterDateRange.value) {
    filters.start_date = dayjs(filterDateRange.value[0]).format('YYYY-MM-DD HH:mm:ss')
    filters.end_date = dayjs(filterDateRange.value[1]).format('YYYY-MM-DD HH:mm:ss')
  }
  currentPage.value = 1
  fetchLogs(filters)
}

function handleReset() {
  filterUsername.value = ''
  filterAction.value = ''
  filterResourceType.value = ''
  filterScenarioId.value = ''
  filterDateRange.value = null
  currentPage.value = 1
  fetchLogs()
}

function showDetail(log: AuditLog) {
  selectedLog.value = log
  detailDrawerOpen.value = true
}

function getActionType(action: string) {
  const map: Record<string, string> = { CREATE: 'success', UPDATE: '', DELETE: 'danger', VIEW: 'info', EXPORT: 'warning' }
  return map[action] || 'info'
}

function formatTime(t: string) { return dayjs(t).format('YYYY-MM-DD HH:mm:ss') }

function handlePageChange(page: number) { currentPage.value = page; fetchLogs() }
function handleSizeChange(size: number) { pageSize.value = size; currentPage.value = 1; fetchLogs() }

onMounted(() => fetchLogs())
</script>

<template>
  <div style="padding: 24px">
    <!-- Filter -->
    <el-card style="margin-bottom: 16px">
      <template #header><span>审计日志查询</span></template>
      <el-form :inline="true" @submit.prevent="handleSearch">
        <el-form-item label="用户名">
          <el-input v-model="filterUsername" placeholder="输入用户名" style="width: 150px" clearable />
        </el-form-item>
        <el-form-item label="操作类型">
          <el-select v-model="filterAction" placeholder="选择操作" style="width: 150px" clearable>
            <el-option label="CREATE" value="CREATE" />
            <el-option label="UPDATE" value="UPDATE" />
            <el-option label="DELETE" value="DELETE" />
            <el-option label="VIEW" value="VIEW" />
            <el-option label="EXPORT" value="EXPORT" />
          </el-select>
        </el-form-item>
        <el-form-item label="资源类型">
          <el-select v-model="filterResourceType" placeholder="选择资源类型" style="width: 150px" clearable>
            <el-option label="USER" value="USER" />
            <el-option label="SCENARIO" value="SCENARIO" />
            <el-option label="KEYWORD" value="KEYWORD" />
            <el-option label="POLICY" value="POLICY" />
            <el-option label="META_TAG" value="META_TAG" />
          </el-select>
        </el-form-item>
        <el-form-item label="场景ID">
          <el-input v-model="filterScenarioId" placeholder="输入场景ID" style="width: 150px" clearable />
        </el-form-item>
        <el-form-item label="时间范围">
          <el-date-picker v-model="filterDateRange" type="datetimerange" range-separator="至" start-placeholder="开始" end-placeholder="结束" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch"><el-icon><Search /></el-icon>查询</el-button>
          <el-button @click="handleReset"><el-icon><Refresh /></el-icon>重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- Table -->
    <el-card>
      <template #header><span>审计日志列表 (共 {{ total }} 条)</span></template>
      <el-table :data="logs" v-loading="loading" row-key="id" style="width: 100%">
        <el-table-column prop="created_at" label="时间" width="180" :formatter="(_r: any, _c: any, v: string) => formatTime(v)" />
        <el-table-column prop="username" label="用户" width="120" />
        <el-table-column prop="action" label="操作" width="100">
          <template #default="{ row }"><el-tag :type="getActionType(row.action)" size="small">{{ row.action }}</el-tag></template>
        </el-table-column>
        <el-table-column prop="resource_type" label="资源类型" width="150" />
        <el-table-column prop="resource_id" label="资源ID" width="200" show-overflow-tooltip />
        <el-table-column prop="scenario_id" label="场景ID" width="150" show-overflow-tooltip />
        <el-table-column prop="ip_address" label="IP地址" width="140" />
        <el-table-column label="操作" width="100" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="showDetail(row)">
              <el-icon><View /></el-icon>详情
            </el-button>
          </template>
        </el-table-column>
      </el-table>
      <div style="margin-top: 16px; display: flex; justify-content: flex-end">
        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :total="total"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
          @current-change="handlePageChange"
          @size-change="handleSizeChange"
        />
      </div>
    </el-card>

    <!-- Detail Drawer -->
    <el-drawer v-model="detailDrawerOpen" title="审计日志详情" direction="rtl" size="600px">
      <template v-if="selectedLog">
        <div style="margin-bottom: 16px"><strong>日志ID:</strong> {{ selectedLog.id }}</div>
        <div style="margin-bottom: 16px"><strong>用户:</strong> {{ selectedLog.username }} (ID: {{ selectedLog.user_id }})</div>
        <div style="margin-bottom: 16px"><strong>操作:</strong> <el-tag :type="getActionType(selectedLog.action)" size="small">{{ selectedLog.action }}</el-tag></div>
        <div style="margin-bottom: 16px"><strong>资源类型:</strong> {{ selectedLog.resource_type }}</div>
        <div v-if="selectedLog.resource_id" style="margin-bottom: 16px"><strong>资源ID:</strong> {{ selectedLog.resource_id }}</div>
        <div v-if="selectedLog.scenario_id" style="margin-bottom: 16px"><strong>场景ID:</strong> {{ selectedLog.scenario_id }}</div>
        <div style="margin-bottom: 16px"><strong>IP地址:</strong> {{ selectedLog.ip_address || 'N/A' }}</div>
        <div style="margin-bottom: 16px">
          <strong>User Agent:</strong>
          <div style="word-break: break-all; font-size: 12px; color: #666">{{ selectedLog.user_agent || 'N/A' }}</div>
        </div>
        <div style="margin-bottom: 16px"><strong>时间:</strong> {{ formatTime(selectedLog.created_at) }}</div>
        <div v-if="selectedLog.details">
          <strong>详细信息:</strong>
          <pre style="background: #f5f5f5; padding: 12px; border-radius: 4px; margin-top: 8px; overflow: auto; max-height: 400px">{{ JSON.stringify(selectedLog.details, null, 2) }}</pre>
        </div>
      </template>
    </el-drawer>
  </div>
</template>

// frontend/src/pages/AuditLogs.tsx
import React, { useState, useEffect } from 'react';
import { Table, Card, Form, Input, Select, DatePicker, Button, Space, Tag, Drawer, message } from 'antd';
import { SearchOutlined, ReloadOutlined, EyeOutlined } from '@ant-design/icons';
import { auditLogsApi, getErrorMessage } from '../api';
import { AuditLog } from '../types';
import dayjs from 'dayjs';

const { RangePicker } = DatePicker;

const AuditLogsPage: React.FC = () => {
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [detailDrawerOpen, setDetailDrawerOpen] = useState(false);
  const [selectedLog, setSelectedLog] = useState<AuditLog | null>(null);
  const [form] = Form.useForm();

  useEffect(() => {
    fetchLogs();
  }, [currentPage, pageSize]);

  const fetchLogs = async (filters?: any) => {
    setLoading(true);
    try {
      const params = {
        skip: (currentPage - 1) * pageSize,
        limit: pageSize,
        ...filters,
      };
      const res = await auditLogsApi.queryLogs(params);
      setLogs(res.data.items || res.data);
      setTotal(res.data.total || res.data.length);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取审计日志失败'));
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (values: any) => {
    const filters: any = {};

    if (values.username) filters.username = values.username;
    if (values.action) filters.action = values.action;
    if (values.resource_type) filters.resource_type = values.resource_type;
    if (values.scenario_id) filters.scenario_id = values.scenario_id;

    if (values.date_range) {
      filters.start_date = values.date_range[0].format('YYYY-MM-DD HH:mm:ss');
      filters.end_date = values.date_range[1].format('YYYY-MM-DD HH:mm:ss');
    }

    setCurrentPage(1);
    fetchLogs(filters);
  };

  const handleReset = () => {
    form.resetFields();
    setCurrentPage(1);
    fetchLogs();
  };

  const showDetail = (log: AuditLog) => {
    setSelectedLog(log);
    setDetailDrawerOpen(true);
  };

  const getActionColor = (action: string) => {
    const colorMap: Record<string, string> = {
      CREATE: 'green',
      UPDATE: 'blue',
      DELETE: 'red',
      VIEW: 'default',
      EXPORT: 'orange',
    };
    return colorMap[action] || 'default';
  };

  const columns = [
    {
      title: '时间',
      dataIndex: 'created_at',
      key: 'created_at',
      width: 180,
      render: (text: string) => dayjs(text).format('YYYY-MM-DD HH:mm:ss'),
    },
    {
      title: '用户',
      dataIndex: 'username',
      key: 'username',
      width: 120,
    },
    {
      title: '操作',
      dataIndex: 'action',
      key: 'action',
      width: 100,
      render: (action: string) => (
        <Tag color={getActionColor(action)}>{action}</Tag>
      ),
    },
    {
      title: '资源类型',
      dataIndex: 'resource_type',
      key: 'resource_type',
      width: 150,
    },
    {
      title: '资源ID',
      dataIndex: 'resource_id',
      key: 'resource_id',
      width: 200,
      ellipsis: true,
    },
    {
      title: '场景ID',
      dataIndex: 'scenario_id',
      key: 'scenario_id',
      width: 150,
      ellipsis: true,
    },
    {
      title: 'IP地址',
      dataIndex: 'ip_address',
      key: 'ip_address',
      width: 140,
    },
    {
      title: '操作',
      key: 'action_btn',
      width: 100,
      fixed: 'right' as const,
      render: (_: any, record: AuditLog) => (
        <Button
          type="link"
          size="small"
          icon={<EyeOutlined />}
          onClick={() => showDetail(record)}
        >
          详情
        </Button>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <Card title="审计日志查询" style={{ marginBottom: 16 }}>
        <Form form={form} onFinish={handleSearch} layout="inline">
          <Form.Item name="username" label="用户名">
            <Input placeholder="输入用户名" style={{ width: 150 }} />
          </Form.Item>
          <Form.Item name="action" label="操作类型">
            <Select placeholder="选择操作" style={{ width: 150 }} allowClear>
              <Select.Option value="CREATE">CREATE</Select.Option>
              <Select.Option value="UPDATE">UPDATE</Select.Option>
              <Select.Option value="DELETE">DELETE</Select.Option>
              <Select.Option value="VIEW">VIEW</Select.Option>
              <Select.Option value="EXPORT">EXPORT</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="resource_type" label="资源类型">
            <Select placeholder="选择资源类型" style={{ width: 150 }} allowClear>
              <Select.Option value="USER">USER</Select.Option>
              <Select.Option value="SCENARIO">SCENARIO</Select.Option>
              <Select.Option value="KEYWORD">KEYWORD</Select.Option>
              <Select.Option value="POLICY">POLICY</Select.Option>
              <Select.Option value="META_TAG">META_TAG</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="scenario_id" label="场景ID">
            <Input placeholder="输入场景ID" style={{ width: 150 }} />
          </Form.Item>
          <Form.Item name="date_range" label="时间范围">
            <RangePicker showTime />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit" icon={<SearchOutlined />}>
                查询
              </Button>
              <Button onClick={handleReset} icon={<ReloadOutlined />}>
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card title={`审计日志列表 (共 ${total} 条)`}>
        <Table
          dataSource={logs}
          columns={columns}
          rowKey="id"
          loading={loading}
          scroll={{ x: 1400 }}
          pagination={{
            current: currentPage,
            pageSize: pageSize,
            total: total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共 ${total} 条`,
            onChange: (page, size) => {
              setCurrentPage(page);
              setPageSize(size);
            },
          }}
        />
      </Card>

      <Drawer
        title="审计日志详情"
        placement="right"
        width={600}
        open={detailDrawerOpen}
        onClose={() => setDetailDrawerOpen(false)}
      >
        {selectedLog && (
          <div>
            <div style={{ marginBottom: 16 }}>
              <strong>日志ID:</strong> {selectedLog.id}
            </div>
            <div style={{ marginBottom: 16 }}>
              <strong>用户:</strong> {selectedLog.username} (ID: {selectedLog.user_id})
            </div>
            <div style={{ marginBottom: 16 }}>
              <strong>操作:</strong> <Tag color={getActionColor(selectedLog.action)}>{selectedLog.action}</Tag>
            </div>
            <div style={{ marginBottom: 16 }}>
              <strong>资源类型:</strong> {selectedLog.resource_type}
            </div>
            {selectedLog.resource_id && (
              <div style={{ marginBottom: 16 }}>
                <strong>资源ID:</strong> {selectedLog.resource_id}
              </div>
            )}
            {selectedLog.scenario_id && (
              <div style={{ marginBottom: 16 }}>
                <strong>场景ID:</strong> {selectedLog.scenario_id}
              </div>
            )}
            <div style={{ marginBottom: 16 }}>
              <strong>IP地址:</strong> {selectedLog.ip_address || 'N/A'}
            </div>
            <div style={{ marginBottom: 16 }}>
              <strong>User Agent:</strong>
              <div style={{ wordBreak: 'break-all', fontSize: 12, color: '#666' }}>
                {selectedLog.user_agent || 'N/A'}
              </div>
            </div>
            <div style={{ marginBottom: 16 }}>
              <strong>时间:</strong> {dayjs(selectedLog.created_at).format('YYYY-MM-DD HH:mm:ss')}
            </div>
            {selectedLog.details && (
              <div>
                <strong>详细信息:</strong>
                <pre style={{
                  background: '#f5f5f5',
                  padding: 12,
                  borderRadius: 4,
                  marginTop: 8,
                  overflow: 'auto',
                  maxHeight: 400,
                }}>
                  {JSON.stringify(selectedLog.details, null, 2)}
                </pre>
              </div>
            )}
          </div>
        )}
      </Drawer>
    </div>
  );
};

export default AuditLogsPage;
