// frontend-vue/src/views/GlobalKeywords.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { GlobalKeyword, MetaTag } from '../types'
import { globalKeywordsApi, metaTagsApi, getErrorMessage } from '../api'

const keywords = ref<GlobalKeyword[]>([])
const tags = ref<MetaTag[]>([])
const loading = ref(false)
const dialogVisible = ref(false)
const editingId = ref<string | null>(null)
const searchText = ref('')
const filterTag = ref('')
const form = ref<Partial<GlobalKeyword>>({ keyword: '', tag_code: '', risk_level: 'Medium', is_active: true })

onMounted(() => { fetchKeywords(); fetchTags() })

async function fetchTags() {
  try { tags.value = (await metaTagsApi.getAll()).data } catch {}
}

async function fetchKeywords() {
  loading.value = true
  try {
    const res = await globalKeywordsApi.getAll(0, 1000, searchText.value || undefined, filterTag.value || undefined)
    keywords.value = res.data
  } catch (e: any) {
    ElMessage.error(getErrorMessage(e, '获取关键词失败'))
  } finally { loading.value = false }
}

function handleAdd() {
  editingId.value = null
  form.value = { keyword: '', tag_code: '', risk_level: 'Medium', is_active: true }
  dialogVisible.value = true
}

function handleEdit(row: GlobalKeyword) {
  editingId.value = row.id
  form.value = { ...row }
  dialogVisible.value = true
}

async function handleDelete(row: GlobalKeyword) {
  try {
    await ElMessageBox.confirm('确定删除此关键词？', '确认', { type: 'warning' })
    await globalKeywordsApi.delete(row.id)
    ElMessage.success('已删除')
    fetchKeywords()
  } catch (e: any) { if (e !== 'cancel') ElMessage.error(getErrorMessage(e, '删除失败')) }
}

async function handleSubmit() {
  try {
    if (editingId.value) {
      await globalKeywordsApi.update(editingId.value, form.value)
      ElMessage.success('已更新')
    } else {
      await globalKeywordsApi.create(form.value as Omit<GlobalKeyword, 'id'>)
      ElMessage.success('已创建')
    }
    dialogVisible.value = false
    fetchKeywords()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '操作失败')) }
}

function getRiskColor(level: string) {
  if (level === 'High') return 'danger'
  if (level === 'Medium') return 'warning'
  return 'success'
}
</script>

<template>
  <div style="padding: 24px">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px">
      <h2 style="margin: 0">全局敏感词库</h2>
      <div style="display: flex; gap: 8px">
        <el-input v-model="searchText" placeholder="搜索关键词" clearable style="width: 200px" @clear="fetchKeywords" @keyup.enter="fetchKeywords" />
        <el-select v-model="filterTag" placeholder="按标签筛选" clearable style="width: 180px" @change="fetchKeywords">
          <el-option v-for="t in tags" :key="t.tag_code" :label="t.tag_name" :value="t.tag_code" />
        </el-select>
        <el-button type="primary" @click="handleAdd">新增关键词</el-button>
      </div>
    </div>

    <el-table :data="keywords" v-loading="loading" border>
      <el-table-column prop="keyword" label="关键词" min-width="200" />
      <el-table-column prop="tag_code" label="标签" width="150" />
      <el-table-column prop="risk_level" label="风险等级" width="120">
        <template #default="{ row }">
          <el-tag :type="getRiskColor(row.risk_level)">{{ row.risk_level }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="is_active" label="状态" width="80">
        <template #default="{ row }">
          <el-tag :type="row.is_active ? 'success' : 'info'" size="small">{{ row.is_active ? '启用' : '禁用' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="160" fixed="right">
        <template #default="{ row }">
          <el-button size="small" @click="handleEdit(row)">编辑</el-button>
          <el-button size="small" type="danger" @click="handleDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog :title="editingId ? '编辑关键词' : '新增关键词'" v-model="dialogVisible" width="500px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="关键词" required>
          <el-input v-model="form.keyword" placeholder="输入敏感词" />
        </el-form-item>
        <el-form-item label="标签" required>
          <el-select v-model="form.tag_code" filterable placeholder="选择标签">
            <el-option v-for="t in tags" :key="t.tag_code" :label="`${t.tag_name} (${t.tag_code})`" :value="t.tag_code" />
          </el-select>
        </el-form-item>
        <el-form-item label="风险等级" required>
          <el-select v-model="form.risk_level">
            <el-option label="High" value="High" /><el-option label="Medium" value="Medium" /><el-option label="Low" value="Low" />
          </el-select>
        </el-form-item>
        <el-form-item label="是否启用">
          <el-switch v-model="form.is_active" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

// frontend/src/pages/GlobalKeywords.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, Select, Switch, Space, message, Popconfirm, Tag } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { GlobalKeyword, MetaTag } from '../types';
import { globalKeywordsApi, metaTagsApi, getErrorMessage } from '../api';

const { Search } = Input;
const { Option } = Select;

const GlobalKeywordsPage: React.FC = () => {
  const [keywords, setKeywords] = useState<GlobalKeyword[]>([]);
  const [tags, setTags] = useState<MetaTag[]>([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [searchText, setSearchText] = useState<string>('');
  const [form] = Form.useForm();

  const fetchKeywords = async (query?: string) => {
    setLoading(true);
    try {
      // Fetching all for simplicity, pagination can be added
      // Passing query for search
      const res = await globalKeywordsApi.getAll(0, 1000, query);
      setKeywords(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取敏感词列表失败'));
    } finally {
      setLoading(false);
    }
  };

  const fetchTags = async () => {
    try {
      const res = await metaTagsApi.getAll();
      setTags(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取标签列表失败'));
    }
  };

  useEffect(() => {
    fetchKeywords();
    fetchTags();
  }, []);

  const handleAdd = () => {
    setEditingId(null);
    form.resetFields();
    form.setFieldsValue({ is_active: true, risk_level: 'High' });
    setIsModalOpen(true);
  };

  const handleEdit = (record: GlobalKeyword) => {
    setEditingId(record.id);
    form.setFieldsValue(record);
    setIsModalOpen(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await globalKeywordsApi.delete(id);
      message.success('敏感词已删除');
      fetchKeywords(searchText);
    } catch (error: any) {
      message.error(getErrorMessage(error, '删除失败'));
    }
  };

  const handleOk = async () => {
    try {
      const values = await form.validateFields();
      if (editingId) {
        await globalKeywordsApi.update(editingId, values);
        message.success('敏感词已更新');
      } else {
        await globalKeywordsApi.create(values);
        message.success('敏感词已创建');
      }
      setIsModalOpen(false);
      fetchKeywords(searchText);
    } catch (error: any) {
      console.error(error);
      if (error.errorFields) {
         // Form validation error, do nothing
      } else {
        message.error(getErrorMessage(error, '操作失败'));
      }
    }
  };
  
  const onSearch = (value: string) => {
    setSearchText(value);
    fetchKeywords(value);
  };

  const columns = [
    { title: '敏感词 (Keyword)', dataIndex: 'keyword', key: 'keyword' },
    { title: '关联标签 (Tag)', dataIndex: 'tag_code', key: 'tag_code', render: (text: string) => <Tag color="blue">{text}</Tag> },
    { 
      title: '风险等级', 
      dataIndex: 'risk_level', 
      key: 'risk_level',
      render: (level: string) => {
        let color = 'default';
        if (level === 'High') color = 'red';
        if (level === 'Medium') color = 'orange';
        if (level === 'Low') color = 'green';
        return <Tag color={color}>{level}</Tag>;
      }
    },
    {
      title: '状态',
      dataIndex: 'is_active',
      key: 'is_active',
      render: (active: boolean) => <Switch size="small" checked={active} disabled />
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: GlobalKeyword) => (
        <Space size="middle">
          <Button icon={<EditOutlined />} onClick={() => handleEdit(record)} />
          <Popconfirm title="确定删除该敏感词吗？" onConfirm={() => handleDelete(record.id)} okText="确定" cancelText="取消">
            <Button icon={<DeleteOutlined />} danger />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>全局敏感词库 (Global Keywords)</h2>
        <Space>
           <Search placeholder="搜索敏感词..." onSearch={onSearch} enterButton allowClear style={{ width: 300 }} />
           <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
             新增敏感词
           </Button>
        </Space>
      </div>

      <Table 
        columns={columns} 
        dataSource={keywords} 
        rowKey="id" 
        loading={loading}
      />

      <Modal 
        title={editingId ? "编辑敏感词" : "新增敏感词"} 
        open={isModalOpen} 
        onOk={handleOk} 
        onCancel={() => setIsModalOpen(false)}
        okText="确定"
        cancelText="取消"
      >
        <Form form={form} layout="vertical">
          <Form.Item name="keyword" label="敏感词内容" rules={[{ required: true, message: '请输入敏感词' }]}>
            <Input placeholder="例如：某些敏感词汇" />
          </Form.Item>
          
          <Form.Item name="tag_code" label="关联标签 (Tag Code)" rules={[{ required: true, message: '请选择标签' }]}>
            <Select placeholder="请选择标签" showSearch optionFilterProp="children">
              {tags.map(tag => (
                <Option key={tag.tag_code} value={tag.tag_code}>{tag.tag_name} ({tag.tag_code})</Option>
              ))}
            </Select>
          </Form.Item>
          
          <Form.Item name="risk_level" label="风险等级" rules={[{ required: true }]}>
            <Select>
              <Select.Option value="High">高 (High)</Select.Option>
              <Select.Option value="Medium">中 (Medium)</Select.Option>
              <Select.Option value="Low">低 (Low)</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="is_active" label="是否启用" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default GlobalKeywordsPage;
