// frontend-vue/src/views/MyScenarios.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { usePermissionStore } from '../stores/permission'

const router = useRouter()
const permStore = usePermissionStore()

const PERMISSION_LABELS: Record<string, string> = {
  scenario_keywords: '敏感词管理',
  scenario_policies: '策略管理',
  scenario_playground: '测试工具',
  scenario_performance: '性能测试',
  scenario_basic_info: '基本信息',
}

const scenarioEntries = computed(() => {
  if (!permStore.userPermissions?.scenario_permissions) return []
  return Object.entries(permStore.userPermissions.scenario_permissions)
})

function goToScenario(appId: string) {
  localStorage.setItem('current_app_id', appId)
  router.push(`/apps/${appId}`)
}
</script>

<template>
  <div style="padding: 24px">
    <el-card>
      <template #header>
        <div style="display: flex; justify-content: space-between; align-items: center">
          <span style="font-size: 18px; font-weight: bold">我的场景</span>
          <el-tag type="primary">{{ scenarioEntries.length }} 个场景</el-tag>
        </div>
      </template>

      <el-empty v-if="permStore.loading" description="加载中..." />
      <el-empty v-else-if="scenarioEntries.length === 0" description="您还没有被分配任何场景" />

      <el-row v-else :gutter="16">
        <el-col v-for="[scenarioId, permissions] in scenarioEntries" :key="scenarioId" :xs="24" :sm="12" :lg="8" :xl="6" style="margin-bottom: 16px">
          <el-card shadow="hover" class="scenario-card" @click="goToScenario(scenarioId)">
            <div style="margin-bottom: 16px; display: flex; align-items: center; gap: 8px">
              <el-icon :size="24" color="#409eff"><Monitor /></el-icon>
              <span style="font-weight: bold; font-size: 16px">{{ scenarioId }}</span>
            </div>
            <div v-if="permissions.length > 0">
              <div style="font-size: 12px; color: #666; margin-bottom: 8px">权限:</div>
              <div style="display: flex; flex-wrap: wrap; gap: 4px">
                <el-tag v-for="perm in permissions" :key="perm" type="success" size="small">
                  {{ PERMISSION_LABELS[perm] || perm }}
                </el-tag>
              </div>
            </div>
            <div style="margin-top: 16px; text-align: right">
              <el-link type="primary">进入管理 →</el-link>
            </div>
          </el-card>
        </el-col>
      </el-row>
    </el-card>
  </div>
</template>

<style scoped>
.scenario-card { cursor: pointer; height: 100%; }
</style>

// frontend/src/pages/MyScenarios.tsx
import React from 'react';
import { Card, List, Tag, Space, Button, Empty, Spin } from 'antd';
import { AppstoreOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { usePermission } from '../hooks/usePermission';

const PERMISSION_LABELS: Record<string, string> = {
  scenario_keywords: '敏感词管理',
  scenario_policies: '策略管理',
  scenario_playground: '测试工具',
  scenario_performance: '性能测试',
  scenario_basic_info: '基本信息',
};

const MyScenarios: React.FC = () => {
  const navigate = useNavigate();
  const { userPermissions, loading } = usePermission();

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: 100 }}>
        <Spin size="large" />
      </div>
    );
  }

  const scenarioEntries = userPermissions?.scenario_permissions
    ? Object.entries(userPermissions.scenario_permissions)
    : [];

  if (scenarioEntries.length === 0) {
    return (
      <Card title="我的场景">
        <Empty description="您还没有被分配任何场景" />
      </Card>
    );
  }

  return (
    <div style={{ padding: 24 }}>
      <Card title="我的场景" extra={<Tag color="blue">{scenarioEntries.length} 个场景</Tag>}>
        <List
          grid={{ gutter: 16, xs: 1, sm: 2, md: 2, lg: 3, xl: 3, xxl: 4 }}
          dataSource={scenarioEntries}
          renderItem={([scenarioId, permissions]) => (
            <List.Item>
              <Card
                hoverable
                onClick={() => navigate(`/apps/${scenarioId}`)}
                style={{ height: '100%' }}
              >
                <div style={{ marginBottom: 16 }}>
                  <Space>
                    <AppstoreOutlined style={{ fontSize: 24, color: '#1890ff' }} />
                    <div style={{ fontWeight: 'bold', fontSize: 16 }}>
                      {scenarioId}
                    </div>
                  </Space>
                </div>

                {permissions.length > 0 && (
                  <div>
                    <div style={{ fontSize: 12, color: '#666', marginBottom: 8 }}>权限:</div>
                    <Space wrap size={[0, 8]}>
                      {permissions.map((perm) => (
                        <Tag key={perm} icon={<CheckCircleOutlined />} color="success">
                          {PERMISSION_LABELS[perm] || perm}
                        </Tag>
                      ))}
                    </Space>
                  </div>
                )}

                <div style={{ marginTop: 16, textAlign: 'right' }}>
                  <Button type="link" size="small">进入管理 →</Button>
                </div>
              </Card>
            </List.Item>
          )}
        />
      </Card>
    </div>
  );
};

export default MyScenarios;
