// frontend-vue/src/views/RolesPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { rolesApi, getErrorMessage } from '../api'
import type { Role, PermissionItem } from '../types'
import { ElMessage, ElMessageBox } from 'element-plus'
import dayjs from 'dayjs'

const roles = ref<Role[]>([])
const allPermissions = ref<PermissionItem[]>([])
const loading = ref(false)
const createModalOpen = ref(false)
const editModalOpen = ref(false)
const permModalOpen = ref(false)
const selectedRole = ref<Role | null>(null)
const selectedPermIds = ref<string[]>([])

const createForm = ref({ role_code: '', role_name: '', role_type: '', description: '' })
const editForm = ref({ role_name: '', role_type: '', description: '' })

const globalPerms = computed(() => allPermissions.value.filter(p => p.scope === 'GLOBAL'))
const scenarioPerms = computed(() => allPermissions.value.filter(p => p.scope === 'SCENARIO'))

async function fetchRoles() {
  loading.value = true
  try { roles.value = (await rolesApi.list()).data }
  catch (e: any) { ElMessage.error(getErrorMessage(e, '获取角色列表失败')) }
  finally { loading.value = false }
}

async function fetchAllPermissions() {
  try { allPermissions.value = (await rolesApi.listAllPermissions()).data } catch { /* ignore */ }
}

async function handleCreate() {
  try {
    await rolesApi.create(createForm.value)
    ElMessage.success('角色创建成功'); createModalOpen.value = false
    createForm.value = { role_code: '', role_name: '', role_type: '', description: '' }
    fetchRoles()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '创建失败')) }
}

async function handleEdit() {
  if (!selectedRole.value) return
  try {
    await rolesApi.update(selectedRole.value.id, editForm.value)
    ElMessage.success('角色更新成功'); editModalOpen.value = false; fetchRoles()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '更新失败')) }
}

async function handleDelete(row: Role) {
  try {
    await ElMessageBox.confirm('确定删除该角色吗?', '确认')
    await rolesApi.delete(row.id); ElMessage.success('角色已删除'); fetchRoles()
  } catch (e: any) { if (e !== 'cancel') ElMessage.error(getErrorMessage(e, '删除失败')) }
}

function openEditModal(role: Role) {
  selectedRole.value = role
  editForm.value = { role_name: role.role_name, role_type: role.role_type, description: role.description || '' }
  editModalOpen.value = true
}

async function openPermModal(role: Role) {
  selectedRole.value = role
  try {
    const res = await rolesApi.getPermissions(role.id)
    selectedPermIds.value = res.data.map((p: PermissionItem) => p.id)
    permModalOpen.value = true
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '获取角色权限失败')) }
}

// PLACEHOLDER_SAVE
async function handleSavePermissions() {
  if (!selectedRole.value) return
  try {
    await rolesApi.updatePermissions(selectedRole.value.id, selectedPermIds.value)
    ElMessage.success('权限配置成功'); permModalOpen.value = false; fetchRoles()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '配置失败')) }
}

function formatTime(t: string) { return dayjs(t).format('YYYY-MM-DD HH:mm') }

onMounted(() => { fetchRoles(); fetchAllPermissions() })
</script>

<template>
  <div style="padding: 24px">
    <div style="margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center">
      <div>
        <h2 style="margin: 0">角色管理</h2>
        <p style="color: #666; margin: 4px 0 0">管理系统角色和权限配置。</p>
      </div>
      <el-button type="primary" @click="createForm = { role_code: '', role_name: '', role_type: '', description: '' }; createModalOpen = true">
        <el-icon><Plus /></el-icon>创建角色
      </el-button>
    </div>

    <el-table :data="roles" v-loading="loading" row-key="id" style="width: 100%">
      <el-table-column prop="role_name" label="角色名称" />
      <el-table-column prop="role_code" label="角色编码" />
      <el-table-column prop="role_type" label="类型" width="100">
        <template #default="{ row }">
          <el-tag :type="row.role_type === 'GLOBAL' ? '' : 'success'" size="small">{{ row.role_type === 'GLOBAL' ? '全局' : '场景' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="permission_count" label="权限数量" width="100" />
      <el-table-column prop="is_system" label="系统角色" width="100">
        <template #default="{ row }">
          <el-tag :type="row.is_system ? 'danger' : 'info'" size="small">{{ row.is_system ? '系统' : '自定义' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="created_at" label="创建时间" width="160" :formatter="(_r: any, _c: any, v: string) => formatTime(v)" />
      <el-table-column label="操作" min-width="260">
        <template #default="{ row }">
          <el-button size="small" @click="openEditModal(row)">编辑</el-button>
          <el-button size="small" @click="openPermModal(row)"><el-icon><Setting /></el-icon>配置权限</el-button>
          <el-button v-if="!row.is_system" size="small" type="danger" @click="handleDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- Create Modal -->
    <el-dialog v-model="createModalOpen" title="创建角色" width="500px">
      <el-form label-position="top">
        <el-form-item label="角色编码" required>
          <el-input v-model="createForm.role_code" placeholder="如: CONTENT_REVIEWER" />
        </el-form-item>
        <el-form-item label="角色名称" required>
          <el-input v-model="createForm.role_name" placeholder="如: 内容审核员" />
        </el-form-item>
        <el-form-item label="角色类型" required>
          <el-select v-model="createForm.role_type" placeholder="请选择" style="width: 100%">
            <el-option label="全局角色" value="GLOBAL" />
            <el-option label="场景角色" value="SCENARIO" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="createForm.description" type="textarea" :rows="3" placeholder="角色描述" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="createModalOpen = false">取消</el-button>
        <el-button type="primary" @click="handleCreate">创建</el-button>
      </template>
    </el-dialog>

    <!-- Edit Modal -->
    <el-dialog v-model="editModalOpen" title="编辑角色" width="500px">
      <el-form label-position="top">
        <el-form-item label="角色名称" required>
          <el-input v-model="editForm.role_name" />
        </el-form-item>
        <el-form-item label="角色类型" required>
          <el-select v-model="editForm.role_type" style="width: 100%">
            <el-option label="全局角色" value="GLOBAL" />
            <el-option label="场景角色" value="SCENARIO" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="editForm.description" type="textarea" :rows="3" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="editModalOpen = false">取消</el-button>
        <el-button type="primary" @click="handleEdit">保存</el-button>
      </template>
    </el-dialog>

    <!-- Permission Modal -->
    <el-dialog v-model="permModalOpen" :title="`配置权限 - ${selectedRole?.role_name}`" width="600px">
      <el-card shadow="never" style="margin-bottom: 16px">
        <template #header><span>全局权限</span></template>
        <el-checkbox-group v-model="selectedPermIds">
          <div v-for="p in globalPerms" :key="p.id" style="margin-bottom: 4px">
            <el-checkbox :value="p.id">{{ p.permission_name }} ({{ p.permission_code }})</el-checkbox>
          </div>
        </el-checkbox-group>
      </el-card>
      <el-card shadow="never">
        <template #header><span>场景权限</span></template>
        <el-checkbox-group v-model="selectedPermIds">
          <div v-for="p in scenarioPerms" :key="p.id" style="margin-bottom: 4px">
            <el-checkbox :value="p.id">{{ p.permission_name }} ({{ p.permission_code }})</el-checkbox>
          </div>
        </el-checkbox-group>
      </el-card>
      <template #footer>
        <el-button @click="permModalOpen = false">取消</el-button>
        <el-button type="primary" @click="handleSavePermissions">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

// frontend/src/pages/RolesPage.tsx
import React, { useState, useEffect } from 'react';
import { Table, Button, Modal, Form, Input, Select, Tag, Space, Popconfirm, message, Card, Checkbox } from 'antd';
import { PlusOutlined, SettingOutlined } from '@ant-design/icons';
import { rolesApi, getErrorMessage } from '../api';
import { Role, PermissionItem } from '../types';
import dayjs from 'dayjs';

const RolesPage: React.FC = () => {
  const [roles, setRoles] = useState<Role[]>([]);
  const [allPermissions, setAllPermissions] = useState<PermissionItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [createModalOpen, setCreateModalOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [permModalOpen, setPermModalOpen] = useState(false);
  const [selectedRole, setSelectedRole] = useState<Role | null>(null);
  const [selectedPermIds, setSelectedPermIds] = useState<string[]>([]);
  const [createForm] = Form.useForm();
  const [editForm] = Form.useForm();

  useEffect(() => {
    fetchRoles();
    fetchAllPermissions();
  }, []);

  const fetchRoles = async () => {
    setLoading(true);
    try {
      const res = await rolesApi.list();
      setRoles(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取角色列表失败'));
    } finally {
      setLoading(false);
    }
  };

  const fetchAllPermissions = async () => {
    try {
      const res = await rolesApi.listAllPermissions();
      setAllPermissions(res.data);
    } catch {
      console.error('Failed to fetch permissions');
    }
  };

  const handleCreate = async (values: any) => {
    try {
      await rolesApi.create(values);
      message.success('角色创建成功');
      setCreateModalOpen(false);
      createForm.resetFields();
      fetchRoles();
    } catch (error: any) {
      message.error(getErrorMessage(error, '创建失败'));
    }
  };

  const handleEdit = async (values: any) => {
    if (!selectedRole) return;
    try {
      await rolesApi.update(selectedRole.id, values);
      message.success('角色更新成功');
      setEditModalOpen(false);
      fetchRoles();
    } catch (error: any) {
      message.error(getErrorMessage(error, '更新失败'));
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await rolesApi.delete(id);
      message.success('角色已删除');
      fetchRoles();
    } catch (error: any) {
      message.error(getErrorMessage(error, '删除失败'));
    }
  };

  const openEditModal = (role: Role) => {
    setSelectedRole(role);
    editForm.setFieldsValue({
      role_name: role.role_name,
      role_type: role.role_type,
      description: role.description,
    });
    setEditModalOpen(true);
  };

  const openPermModal = async (role: Role) => {
    setSelectedRole(role);
    try {
      const res = await rolesApi.getPermissions(role.id);
      const permIds = res.data.map((p: PermissionItem) => p.id);
      setSelectedPermIds(permIds);
      setPermModalOpen(true);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取角色权限失败'));
    }
  };

  const handleSavePermissions = async () => {
    if (!selectedRole) return;
    try {
      await rolesApi.updatePermissions(selectedRole.id, selectedPermIds);
      message.success('权限配置成功');
      setPermModalOpen(false);
      fetchRoles();
    } catch (error: any) {
      message.error(getErrorMessage(error, '配置失败'));
    }
  };

  const globalPerms = allPermissions.filter(p => p.scope === 'GLOBAL');
  const scenarioPerms = allPermissions.filter(p => p.scope === 'SCENARIO');

  const columns = [
    { title: '角色名称', dataIndex: 'role_name', key: 'role_name' },
    { title: '角色编码', dataIndex: 'role_code', key: 'role_code' },
    {
      title: '类型',
      dataIndex: 'role_type',
      key: 'role_type',
      render: (t: string) => (
        <Tag color={t === 'GLOBAL' ? 'blue' : 'green'}>{t === 'GLOBAL' ? '全局' : '场景'}</Tag>
      ),
    },
    {
      title: '权限数量',
      dataIndex: 'permission_count',
      key: 'permission_count',
    },
    {
      title: '系统角色',
      dataIndex: 'is_system',
      key: 'is_system',
      render: (v: boolean) => v ? <Tag color="red">系统</Tag> : <Tag>自定义</Tag>,
    },
    {
      title: '创建时间',
      dataIndex: 'created_at',
      key: 'created_at',
      render: (d: string) => dayjs(d).format('YYYY-MM-DD HH:mm'),
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: Role) => (
        <Space>
          <Button size="small" onClick={() => openEditModal(record)}>编辑</Button>
          <Button size="small" icon={<SettingOutlined />} onClick={() => openPermModal(record)}>配置权限</Button>
          {!record.is_system && (
            <Popconfirm title="确定删除该角色吗?" onConfirm={() => handleDelete(record.id)}>
              <Button size="small" danger>删除</Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2>角色管理</h2>
          <p style={{ color: '#666' }}>管理系统角色和权限配置。</p>
        </div>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => { createForm.resetFields(); setCreateModalOpen(true); }}>
          创建角色
        </Button>
      </div>

      <Table dataSource={roles} columns={columns} rowKey="id" loading={loading} />

      <Modal title="创建角色" open={createModalOpen} onCancel={() => setCreateModalOpen(false)} footer={null}>
        <Form form={createForm} onFinish={handleCreate} layout="vertical">
          <Form.Item name="role_code" label="角色编码" rules={[{ required: true, message: '请输入角色编码' }]}>
            <Input placeholder="如: CONTENT_REVIEWER" />
          </Form.Item>
          <Form.Item name="role_name" label="角色名称" rules={[{ required: true, message: '请输入角色名称' }]}>
            <Input placeholder="如: 内容审核员" />
          </Form.Item>
          <Form.Item name="role_type" label="角色类型" rules={[{ required: true, message: '请选择角色类型' }]}>
            <Select placeholder="请选择">
              <Select.Option value="GLOBAL">全局角色</Select.Option>
              <Select.Option value="SCENARIO">场景角色</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="description" label="描述">
            <Input.TextArea rows={3} placeholder="角色描述" />
          </Form.Item>
          <Form.Item>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <Button onClick={() => setCreateModalOpen(false)}>取消</Button>
              <Button type="primary" htmlType="submit">创建</Button>
            </div>
          </Form.Item>
        </Form>
      </Modal>

      <Modal title="编辑角色" open={editModalOpen} onCancel={() => setEditModalOpen(false)} footer={null}>
        <Form form={editForm} onFinish={handleEdit} layout="vertical">
          <Form.Item name="role_name" label="角色名称" rules={[{ required: true, message: '请输入角色名称' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="role_type" label="角色类型" rules={[{ required: true, message: '请选择角色类型' }]}>
            <Select>
              <Select.Option value="GLOBAL">全局角色</Select.Option>
              <Select.Option value="SCENARIO">场景角色</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item name="description" label="描述">
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <Button onClick={() => setEditModalOpen(false)}>取消</Button>
              <Button type="primary" htmlType="submit">保存</Button>
            </div>
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title={`配置权限 - ${selectedRole?.role_name}`}
        open={permModalOpen}
        onCancel={() => setPermModalOpen(false)}
        onOk={handleSavePermissions}
        width={600}
      >
        <Card size="small" title="全局权限" style={{ marginBottom: 16 }}>
          <Checkbox.Group
            value={selectedPermIds}
            onChange={(vals) => {
              const scenarioSelected = selectedPermIds.filter(id => scenarioPerms.some(p => p.id === id));
              setSelectedPermIds([...scenarioSelected, ...(vals as string[])]);
            }}
          >
            <Space direction="vertical">
              {globalPerms.map(p => (
                <Checkbox key={p.id} value={p.id}>{p.permission_name} ({p.permission_code})</Checkbox>
              ))}
            </Space>
          </Checkbox.Group>
        </Card>
        <Card size="small" title="场景权限">
          <Checkbox.Group
            value={selectedPermIds}
            onChange={(vals) => {
              const globalSelected = selectedPermIds.filter(id => globalPerms.some(p => p.id === id));
              setSelectedPermIds([...globalSelected, ...(vals as string[])]);
            }}
          >
            <Space direction="vertical">
              {scenarioPerms.map(p => (
                <Checkbox key={p.id} value={p.id}>{p.permission_name} ({p.permission_code})</Checkbox>
              ))}
            </Space>
          </Checkbox.Group>
        </Card>
      </Modal>
    </div>
  );
};

export default RolesPage;
