// frontend/src/pages/AnnotatorStats.tsx
import React, { useState, useEffect } from 'react';
import { Card, Table, Statistic, Row, Col, Select, message, Spin } from 'antd';
import { UserOutlined, CheckCircleOutlined, CloseCircleOutlined, FileTextOutlined } from '@ant-design/icons';
import { stagingApi, getErrorMessage } from '../api';

const { Option } = Select;

interface AnnotatorStat {
  annotator: string;
  reviewed_count: number;
  ignored_count: number;
  total_count: number;
}

const AnnotatorStatsPage: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [taskType, setTaskType] = useState('keywords');
  const [stats, setStats] = useState<AnnotatorStat[]>([]);

  useEffect(() => {
    fetchStats();
  }, [taskType]);

  const fetchStats = async () => {
    setLoading(true);
    try {
      const res = await stagingApi.getAnnotatorStats(taskType);
      setStats(res.data);
    } catch (e: any) {
      message.error(getErrorMessage(e, '获取统计数据失败'));
    } finally {
      setLoading(false);
    }
  };

  // 计算总计
  const totalReviewed = stats.reduce((sum, item) => sum + item.reviewed_count, 0);
  const totalIgnored = stats.reduce((sum, item) => sum + item.ignored_count, 0);
  const totalAll = stats.reduce((sum, item) => sum + item.total_count, 0);

  const columns = [
    {
      title: '标注员',
      dataIndex: 'annotator',
      key: 'annotator',
      render: (name: string) => (
        <span>
          <UserOutlined style={{ marginRight: 8 }} />
          {name}
        </span>
      ),
    },
    {
      title: '已审核',
      dataIndex: 'reviewed_count',
      key: 'reviewed_count',
      sorter: (a: AnnotatorStat, b: AnnotatorStat) => a.reviewed_count - b.reviewed_count,
      render: (count: number) => (
        <span style={{ color: '#52c41a', fontWeight: 'bold' }}>
          <CheckCircleOutlined style={{ marginRight: 4 }} />
          {count}
        </span>
      ),
    },
    {
      title: '已忽略',
      dataIndex: 'ignored_count',
      key: 'ignored_count',
      sorter: (a: AnnotatorStat, b: AnnotatorStat) => a.ignored_count - b.ignored_count,
      render: (count: number) => (
        <span style={{ color: '#999' }}>
          <CloseCircleOutlined style={{ marginRight: 4 }} />
          {count}
        </span>
      ),
    },
    {
      title: '总计',
      dataIndex: 'total_count',
      key: 'total_count',
      sorter: (a: AnnotatorStat, b: AnnotatorStat) => a.total_count - b.total_count,
      render: (count: number) => (
        <span style={{ fontWeight: 'bold' }}>
          <FileTextOutlined style={{ marginRight: 4 }} />
          {count}
        </span>
      ),
    },
    {
      title: '完成率',
      key: 'completion_rate',
      sorter: (a: AnnotatorStat, b: AnnotatorStat) => {
        const rateA = a.total_count > 0 ? ((a.reviewed_count + a.ignored_count) / a.total_count) * 100 : 0;
        const rateB = b.total_count > 0 ? ((b.reviewed_count + b.ignored_count) / b.total_count) * 100 : 0;
        return rateA - rateB;
      },
      render: (_: any, record: AnnotatorStat) => {
        const rate = record.total_count > 0
          ? ((record.reviewed_count + record.ignored_count) / record.total_count) * 100
          : 0;
        return <span>{rate.toFixed(1)}%</span>;
      },
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <h2>标注员统计 (Annotator Statistics)</h2>
        <Select
          value={taskType}
          onChange={setTaskType}
          style={{ width: 200 }}
        >
          <Option value="keywords">敏感词审核</Option>
          <Option value="rules">规则审核</Option>
        </Select>
      </div>

      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col span={6}>
          <Card>
            <Statistic
              title="总标注员数"
              value={stats.length}
              prefix={<UserOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="总已审核"
              value={totalReviewed}
              valueStyle={{ color: '#3f8600' }}
              prefix={<CheckCircleOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="总已忽略"
              value={totalIgnored}
              valueStyle={{ color: '#999' }}
              prefix={<CloseCircleOutlined />}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic
              title="总标注数"
              value={totalAll}
              prefix={<FileTextOutlined />}
            />
          </Card>
        </Col>
      </Row>

      <Card>
        <Spin spinning={loading}>
          <Table
            columns={columns}
            dataSource={stats}
            rowKey="annotator"
            pagination={{ pageSize: 10 }}
            locale={{ emptyText: '暂无标注数据' }}
          />
        </Spin>
      </Card>
    </div>
  );
};

export default AnnotatorStatsPage;

// frontend-vue/src/views/AnnotatorStats.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { stagingApi, getErrorMessage } from '../api'
import { ElMessage } from 'element-plus'

const loading = ref(false)
const taskType = ref('keywords')
const stats = ref<any[]>([])

const totalReviewed = computed(() => stats.value.reduce((s, i) => s + i.reviewed_count, 0))
const totalIgnored = computed(() => stats.value.reduce((s, i) => s + i.ignored_count, 0))
const totalAll = computed(() => stats.value.reduce((s, i) => s + i.total_count, 0))

async function fetchStats() {
  loading.value = true
  try {
    const res = await stagingApi.getAnnotatorStats(taskType.value)
    stats.value = res.data
  } catch (e: any) {
    ElMessage.error(getErrorMessage(e, '获取统计数据失败'))
  } finally {
    loading.value = false
  }
}

function completionRate(row: any) {
  return row.total_count > 0
    ? (((row.reviewed_count + row.ignored_count) / row.total_count) * 100).toFixed(1) + '%'
    : '0.0%'
}

onMounted(fetchStats)
watch(taskType, fetchStats)
</script>

<template>
  <div style="padding: 24px">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px">
      <h2 style="margin: 0">标注员统计 (Annotator Statistics)</h2>
      <el-select v-model="taskType" style="width: 200px">
        <el-option label="敏感词审核" value="keywords" />
        <el-option label="规则审核" value="rules" />
      </el-select>
    </div>

    <el-row :gutter="16" style="margin-bottom: 24px">
      <el-col :span="6">
        <el-card shadow="never">
          <el-statistic title="总标注员数" :value="stats.length">
            <template #prefix><el-icon><User /></el-icon></template>
          </el-statistic>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="never">
          <el-statistic title="总已审核" :value="totalReviewed" :value-style="{ color: '#3f8600' }">
            <template #prefix><el-icon><CircleCheck /></el-icon></template>
          </el-statistic>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="never">
          <el-statistic title="总已忽略" :value="totalIgnored" :value-style="{ color: '#999' }">
            <template #prefix><el-icon><CircleClose /></el-icon></template>
          </el-statistic>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="never">
          <el-statistic title="总标注数" :value="totalAll">
            <template #prefix><el-icon><Document /></el-icon></template>
          </el-statistic>
        </el-card>
      </el-col>
    </el-row>

    <el-card>
      <el-table :data="stats" v-loading="loading" row-key="annotator" style="width: 100%">
        <el-table-column prop="annotator" label="标注员">
          <template #default="{ row }">
            <el-icon style="margin-right: 4px"><User /></el-icon>{{ row.annotator }}
          </template>
        </el-table-column>
        <el-table-column prop="reviewed_count" label="已审核" sortable>
          <template #default="{ row }">
            <span style="color: #52c41a; font-weight: bold">{{ row.reviewed_count }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="ignored_count" label="已忽略" sortable>
          <template #default="{ row }">
            <span style="color: #999">{{ row.ignored_count }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="total_count" label="总计" sortable>
          <template #default="{ row }">
            <span style="font-weight: bold">{{ row.total_count }}</span>
          </template>
        </el-table-column>
        <el-table-column label="完成率" sortable :sort-method="(a: any, b: any) => (a.total_count > 0 ? (a.reviewed_count + a.ignored_count) / a.total_count : 0) - (b.total_count > 0 ? (b.reviewed_count + b.ignored_count) / b.total_count : 0)">
          <template #default="{ row }">{{ completionRate(row) }}</template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>
