// frontend/src/pages/MetaTags.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, InputNumber, Switch, Space, message, Popconfirm } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { MetaTag } from '../types';
import { metaTagsApi, getErrorMessage } from '../api';

const MetaTagsPage: React.FC = () => {
  const [tags, setTags] = useState<MetaTag[]>([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form] = Form.useForm();

  const fetchTags = async () => {
    setLoading(true);
    try {
      const res = await metaTagsApi.getAll();
      setTags(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取标签列表失败'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTags();
  }, []);

  const handleAdd = () => {
    setEditingId(null);
    form.resetFields();
    // Default values
    form.setFieldsValue({ level: 2, is_active: true });
    setIsModalOpen(true);
  };

  const handleEdit = (record: MetaTag) => {
    setEditingId(record.id);
    form.setFieldsValue(record);
    setIsModalOpen(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await metaTagsApi.delete(id);
      message.success('标签已删除');
      fetchTags();
    } catch (error: any) {
      message.error(getErrorMessage(error, '删除失败'));
    }
  };

  const handleOk = async () => {
    try {
      const values = await form.validateFields();
      if (editingId) {
        await metaTagsApi.update(editingId, values);
        message.success('标签已更新');
      } else {
        await metaTagsApi.create(values);
        message.success('标签已创建');
      }
      setIsModalOpen(false);
      fetchTags();
    } catch (error) {
      // Form validation error or API error
      console.error(error);
    }
  };

  const columns = [
    { title: '标签编码 (Code)', dataIndex: 'tag_code', key: 'tag_code' },
    { title: '标签名称', dataIndex: 'tag_name', key: 'tag_name' },
    { title: '父级编码', dataIndex: 'parent_code', key: 'parent_code' },
    { title: '层级 (Level)', dataIndex: 'level', key: 'level' },
    {
      title: '状态',
      dataIndex: 'is_active',
      key: 'is_active',
      render: (active: boolean) => <Switch size="small" checked={active} disabled />
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: MetaTag) => (
        <Space size="middle">
          <Button icon={<EditOutlined />} onClick={() => handleEdit(record)} />
          <Popconfirm title="确定删除该标签吗？" onConfirm={() => handleDelete(record.id)} okText="确定" cancelText="取消">
            <Button icon={<DeleteOutlined />} danger />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>标签管理 (Meta Tags)</h2>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
          新增标签
        </Button>
      </div>
      
      <Table 
        columns={columns} 
        dataSource={tags} 
        rowKey="id" 
        loading={loading}
      />

      <Modal 
        title={editingId ? "编辑标签" : "新增标签"} 
        open={isModalOpen} 
        onOk={handleOk} 
        onCancel={() => setIsModalOpen(false)}
        okText="确定"
        cancelText="取消"
      >
        <Form form={form} layout="vertical">
          <Form.Item name="tag_code" label="标签编码 (Tag Code)" rules={[{ required: true, message: '请输入标签编码' }]}>
            <Input disabled={!!editingId} placeholder="例如：POLITICS" /> 
          </Form.Item>
          <Form.Item name="tag_name" label="标签名称" rules={[{ required: true, message: '请输入标签名称' }]}>
            <Input placeholder="例如：政治敏感" />
          </Form.Item>
          <Form.Item name="parent_code" label="父级编码 (Parent Code)">
            <Input placeholder="可选" />
          </Form.Item>
          <Form.Item name="level" label="层级 (Level)" rules={[{ required: true }]}>
            <InputNumber min={1} />
          </Form.Item>
          <Form.Item name="is_active" label="是否启用" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default MetaTagsPage;

// frontend-vue/src/views/MetaTags.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { MetaTag } from '../types'
import { metaTagsApi, getErrorMessage } from '../api'

const tags = ref<MetaTag[]>([])
const loading = ref(false)
const dialogVisible = ref(false)
const editingId = ref<string | null>(null)
const form = ref<Partial<MetaTag>>({ tag_code: '', tag_name: '', parent_code: '', level: 1, is_active: true })

onMounted(() => fetchTags())

async function fetchTags() {
  loading.value = true
  try {
    const res = await metaTagsApi.getAll()
    tags.value = res.data
  } catch (e: any) {
    ElMessage.error(getErrorMessage(e, '获取标签列表失败'))
  } finally {
    loading.value = false
  }
}

function handleAdd() {
  editingId.value = null
  form.value = { tag_code: '', tag_name: '', parent_code: '', level: 1, is_active: true }
  dialogVisible.value = true
}

function handleEdit(row: MetaTag) {
  editingId.value = row.id
  form.value = { ...row }
  dialogVisible.value = true
}

async function handleDelete(row: MetaTag) {
  try {
    await ElMessageBox.confirm('确定要删除此标签吗？', '确认删除', { type: 'warning' })
    await metaTagsApi.delete(row.id)
    ElMessage.success('标签已删除')
    fetchTags()
  } catch (e: any) {
    if (e !== 'cancel') ElMessage.error(getErrorMessage(e, '删除失败'))
  }
}

async function handleSubmit() {
  try {
    if (editingId.value) {
      await metaTagsApi.update(editingId.value, form.value)
      ElMessage.success('标签已更新')
    } else {
      await metaTagsApi.create(form.value as Omit<MetaTag, 'id'>)
      ElMessage.success('标签已创建')
    }
    dialogVisible.value = false
    fetchTags()
  } catch (e: any) {
    ElMessage.error(getErrorMessage(e, '操作失败'))
  }
}
</script>

<template>
  <div style="padding: 24px">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px">
      <div>
        <h2 style="margin: 0">标签管理</h2>
        <p style="color: #666; margin: 4px 0 0">管理内容分类标签体系</p>
      </div>
      <el-button type="primary" @click="handleAdd">新增标签</el-button>
    </div>

    <el-table :data="tags" v-loading="loading" row-key="id" border>
      <el-table-column prop="tag_code" label="标签编码" width="200" />
      <el-table-column prop="tag_name" label="标签名称" width="200" />
      <el-table-column prop="parent_code" label="父级编码" width="200">
        <template #default="{ row }">{{ row.parent_code || '-' }}</template>
      </el-table-column>
      <el-table-column prop="level" label="层级" width="80" />
      <el-table-column prop="is_active" label="状态" width="100">
        <template #default="{ row }">
          <el-tag :type="row.is_active ? 'success' : 'info'">{{ row.is_active ? '启用' : '禁用' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="180" fixed="right">
        <template #default="{ row }">
          <el-button size="small" @click="handleEdit(row)">编辑</el-button>
          <el-button size="small" type="danger" @click="handleDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog :title="editingId ? '编辑标签' : '新增标签'" v-model="dialogVisible" width="500px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="标签编码" required>
          <el-input v-model="form.tag_code" :disabled="!!editingId" placeholder="如: POLITICS" />
        </el-form-item>
        <el-form-item label="标签名称" required>
          <el-input v-model="form.tag_name" placeholder="如: 政治敏感" />
        </el-form-item>
        <el-form-item label="父级编码">
          <el-select v-model="form.parent_code" clearable filterable placeholder="选择父级标签">
            <el-option v-for="t in tags" :key="t.tag_code" :label="`${t.tag_name} (${t.tag_code})`" :value="t.tag_code" />
          </el-select>
        </el-form-item>
        <el-form-item label="层级">
          <el-input-number v-model="form.level" :min="1" :max="5" />
        </el-form-item>
        <el-form-item label="是否启用">
          <el-switch v-model="form.is_active" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>
