// frontend/src/pages/ScenarioPolicies.tsx
import React, { useState, useEffect } from 'react';
import { Tabs, Button, Card, Row, Col, Input, message, Result } from 'antd';
import { SearchOutlined, ArrowLeftOutlined, LockOutlined } from '@ant-design/icons';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import ScenarioKeywordsTab from '../components/ScenarioKeywordsTab';
import ScenarioRulesTab from '../components/ScenarioRulesTab';
import { usePermission } from '../hooks/usePermission';

const { TabPane } = Tabs;

const ScenarioPoliciesPage: React.FC = () => {
  const { appId } = useParams<{ appId: string }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { hasPermission, hasScenarioPermission } = usePermission();

  const [currentScenarioId, setCurrentScenarioId] = useState<string>('');
  const [searchScenarioId, setSearchScenarioId] = useState<string>('');
  const [activeMode, setActiveMode] = useState<'custom' | 'super'>('custom');
  const [activeTab, setActiveTab] = useState<string>('keywords');

  // Initial load from URL
  useEffect(() => {
    if (appId) {
      setCurrentScenarioId(appId);
      setSearchScenarioId(appId);
    }

    const modeParam = searchParams.get('mode');
    if (modeParam === 'custom' || modeParam === 'super') {
      setActiveMode(modeParam);
    }

    const tabParam = searchParams.get('tab');
    if (tabParam) {
      setActiveTab(tabParam);
    }
  }, [appId, searchParams]);

  const handleSearch = () => {
    if (searchScenarioId.trim()) {
      setCurrentScenarioId(searchScenarioId.trim());
    } else {
      message.warning('请输入场景 ID');
    }
  };

  // 权限检查：全局权限或场景级权限
  const canKeywords = currentScenarioId
    ? hasPermission('scenario_keywords') || hasScenarioPermission(currentScenarioId, 'scenario_keywords')
    : false;
  const canPolicies = currentScenarioId
    ? hasPermission('scenario_policies') || hasScenarioPermission(currentScenarioId, 'scenario_policies')
    : false;
  const hasAnyAccess = canKeywords || canPolicies;

  // 默认选中有权限的 tab
  useEffect(() => {
    if (currentScenarioId && !searchParams.get('tab')) {
      if (canKeywords) setActiveTab('keywords');
      else if (canPolicies) setActiveTab('rules');
    }
  }, [currentScenarioId, canKeywords, canPolicies]);

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        {appId && (
          <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(`/apps/${appId}`)} style={{ marginBottom: 16 }}>
            返回应用概览
          </Button>
        )}
        <h2>场景策略管理 {appId ? `- ${appId}` : ''}</h2>

        {!appId && (
          <Card title="选择场景" style={{ marginBottom: 16 }}>
            <Row gutter={16} align="middle">
              <Col>
                <span>场景 ID (Scenario ID): </span>
              </Col>
              <Col flex="auto">
                <Input
                  placeholder="请输入场景 ID"
                  value={searchScenarioId}
                  onChange={e => setSearchScenarioId(e.target.value)}
                  onPressEnter={handleSearch}
                />
              </Col>
              <Col>
                <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                  加载策略
                </Button>
              </Col>
            </Row>
          </Card>
        )}
      </div>

      {currentScenarioId && !hasAnyAccess && (
        <Result
          icon={<LockOutlined />}
          title="权限不足"
          subTitle="您没有该场景的敏感词管理或策略管理权限"
          extra={appId && (
            <Button type="primary" onClick={() => navigate(-1)}>返回</Button>
          )}
        />
      )}

      {currentScenarioId && hasAnyAccess && (
        <Tabs
          activeKey={activeMode}
          onChange={(key) => setActiveMode(key as 'custom' | 'super')}
          type="card"
        >
          <TabPane tab="自定义模式管理" key="custom">
            <Tabs activeKey={activeTab} onChange={setActiveTab} type="line">
              {canKeywords && (
                <TabPane tab="敏感词管理（黑名单/白名单）" key="keywords">
                  <ScenarioKeywordsTab scenarioId={currentScenarioId} mode="custom" />
                </TabPane>
              )}
              {canPolicies && (
                <TabPane tab="规则管理" key="rules">
                  <ScenarioRulesTab scenarioId={currentScenarioId} ruleMode={1} modeName="自定义模式" />
                </TabPane>
              )}
            </Tabs>
          </TabPane>

          <TabPane tab="超级模式管理" key="super">
            <Tabs activeKey={activeTab} onChange={setActiveTab} type="line">
              {canKeywords && (
                <TabPane tab="敏感词管理（黑名单/白名单）" key="keywords">
                  <ScenarioKeywordsTab scenarioId={currentScenarioId} mode="super" />
                </TabPane>
              )}
              {canPolicies && (
                <TabPane tab="规则管理" key="rules">
                  <ScenarioRulesTab scenarioId={currentScenarioId} ruleMode={0} modeName="超级模式" />
                </TabPane>
              )}
            </Tabs>
          </TabPane>
        </Tabs>
      )}
    </div>
  );
};

export default ScenarioPoliciesPage;

// frontend-vue/src/views/ScenarioPolicies.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import ScenarioKeywordsTab from '../components/ScenarioKeywordsTab.vue'
import ScenarioRulesTab from '../components/ScenarioRulesTab.vue'
import { usePermissionStore } from '../stores/permission'

const route = useRoute()
const router = useRouter()
const permStore = usePermissionStore()
const appId = computed(() => route.params.appId as string)

const currentScenarioId = ref('')
const searchScenarioId = ref('')
const activeMode = ref<'custom' | 'super'>('custom')
const activeTab = ref('keywords')

onMounted(() => {
  if (appId.value) { currentScenarioId.value = appId.value; searchScenarioId.value = appId.value }
  const modeParam = route.query.mode as string
  if (modeParam === 'custom' || modeParam === 'super') activeMode.value = modeParam
  const tabParam = route.query.tab as string
  if (tabParam) activeTab.value = tabParam
})

function handleSearch() {
  if (searchScenarioId.value.trim()) currentScenarioId.value = searchScenarioId.value.trim()
  else ElMessage.warning('请输入场景 ID')
}

const canKeywords = computed(() => currentScenarioId.value
  ? permStore.hasPermission('scenario_keywords') || permStore.hasScenarioPermission(currentScenarioId.value, 'scenario_keywords')
  : false)
const canPolicies = computed(() => currentScenarioId.value
  ? permStore.hasPermission('scenario_policies') || permStore.hasScenarioPermission(currentScenarioId.value, 'scenario_policies')
  : false)
const hasAnyAccess = computed(() => canKeywords.value || canPolicies.value)

watch([currentScenarioId, canKeywords, canPolicies], () => {
  if (currentScenarioId.value && !route.query.tab) {
    if (canKeywords.value) activeTab.value = 'keywords'
    else if (canPolicies.value) activeTab.value = 'rules'
  }
})
</script>

<template>
  <div style="padding: 24px">
    <el-button v-if="appId" @click="router.push(`/apps/${appId}`)" style="margin-bottom:16px">返回应用概览</el-button>
    <h2>场景策略管理 {{ appId ? `- ${appId}` : '' }}</h2>

    <el-card v-if="!appId" style="margin-bottom:16px">
      <template #header>选择场景</template>
      <div style="display:flex;gap:8px;align-items:center">
        <span>场景 ID:</span>
        <el-input v-model="searchScenarioId" placeholder="请输入场景 ID" style="flex:1" @keyup.enter="handleSearch" />
        <el-button type="primary" @click="handleSearch">加载策略</el-button>
      </div>
    </el-card>

    <el-result v-if="currentScenarioId && !hasAnyAccess" icon="warning" title="权限不足" sub-title="您没有该场景的敏感词管理或策略管理权限">
      <template #extra><el-button v-if="appId" type="primary" @click="router.back()">返回</el-button></template>
    </el-result>

    <el-tabs v-if="currentScenarioId && hasAnyAccess" v-model="activeMode" type="card">
      <el-tab-pane label="自定义模式管理" name="custom">
        <el-tabs v-model="activeTab">
          <el-tab-pane v-if="canKeywords" label="敏感词管理（黑名单/白名单）" name="keywords">
            <ScenarioKeywordsTab :scenario-id="currentScenarioId" mode="custom" />
          </el-tab-pane>
          <el-tab-pane v-if="canPolicies" label="规则管理" name="rules">
            <ScenarioRulesTab :scenario-id="currentScenarioId" :rule-mode="1" mode-name="自定义模式" />
          </el-tab-pane>
        </el-tabs>
      </el-tab-pane>
      <el-tab-pane label="超级模式管理" name="super">
        <el-tabs v-model="activeTab">
          <el-tab-pane v-if="canKeywords" label="敏感词管理（黑名单/白名单）" name="keywords">
            <ScenarioKeywordsTab :scenario-id="currentScenarioId" mode="super" />
          </el-tab-pane>
          <el-tab-pane v-if="canPolicies" label="规则管理" name="rules">
            <ScenarioRulesTab :scenario-id="currentScenarioId" :rule-mode="0" mode-name="超级模式" />
          </el-tab-pane>
        </el-tabs>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>
