// frontend/src/pages/UsersPage.tsx
import React, { useState, useEffect } from 'react';
import { Table, Button, Modal, Form, message, Tag, Space, Popconfirm, Switch, Select, Drawer, Card } from 'antd';
import { DeleteOutlined, TeamOutlined, EyeOutlined } from '@ant-design/icons';
import { usersApi, userRolesApi, rolesApi, scenariosApi, getErrorMessage } from '../api';
import { User, ScenarioApp, Role, UserRoleAssignment } from '../types';
import dayjs from 'dayjs';

const UsersPage: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [roles, setRoles] = useState<Role[]>([]);
  const [scenarios, setScenarios] = useState<ScenarioApp[]>([]);
  const [loading, setLoading] = useState(false);
  const [assignRoleModalOpen, setAssignRoleModalOpen] = useState(false);
  const [rolesDrawerOpen, setRolesDrawerOpen] = useState(false);
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [userRoleAssignments, setUserRoleAssignments] = useState<UserRoleAssignment[]>([]);
  const [selectedRoleType, setSelectedRoleType] = useState<string>('');
  const [assignForm] = Form.useForm();

  useEffect(() => {
    fetchUsers();
    fetchRoles();
    fetchScenarios();
  }, []);

  const fetchUsers = async () => {
    setLoading(true);
    try {
      const res = await usersApi.list();
      setUsers(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取用户列表失败'));
    } finally {
      setLoading(false);
    }
  };

  const fetchRoles = async () => {
    try {
      const res = await rolesApi.list();
      setRoles(res.data);
    } catch {
      console.error('Failed to fetch roles');
    }
  };

  const fetchScenarios = async () => {
    try {
      const res = await scenariosApi.getAll();
      setScenarios(res.data);
    } catch {
      console.error('Failed to fetch scenarios');
    }
  };
  const handleStatusChange = async (id: string, checked: boolean) => {
    try {
      await usersApi.updateStatus(id, checked);
      message.success('状态已更新');
      fetchUsers();
    } catch (error: any) {
      message.error(getErrorMessage(error, '更新失败'));
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await usersApi.delete(id);
      message.success('用户已删除');
      fetchUsers();
    } catch (error: any) {
      message.error(getErrorMessage(error, '删除失败'));
    }
  };

  const openAssignRoleModal = (user: User) => {
    setSelectedUser(user);
    setSelectedRoleType('');
    assignForm.resetFields();
    setAssignRoleModalOpen(true);
  };

  const handleAssignRole = async (values: any) => {
    if (!selectedUser) return;
    try {
      const data: { role_id: string; scenario_id?: string } = { role_id: values.role_id };
      if (values.scenario_id) {
        data.scenario_id = values.scenario_id;
      }
      await userRolesApi.assignRole(selectedUser.id, data);
      message.success('角色分配成功');
      setAssignRoleModalOpen(false);
      fetchUsers();
    } catch (error: any) {
      message.error(getErrorMessage(error, '分配失败'));
    }
  };

  const openRolesDrawer = async (user: User) => {
    setSelectedUser(user);
    try {
      const res = await userRolesApi.getUserRoles(user.id);
      setUserRoleAssignments(res.data);
      setRolesDrawerOpen(true);
    } catch (error: any) {
      message.error(getErrorMessage(error, '获取用户角色失败'));
    }
  };

  const handleRemoveRole = async (userId: string, assignmentId: string) => {
    try {
      await userRolesApi.removeRole(userId, assignmentId);
      message.success('角色已移除');
      const res = await userRolesApi.getUserRoles(userId);
      setUserRoleAssignments(res.data);
    } catch (error: any) {
      message.error(getErrorMessage(error, '移除失败'));
    }
  };

  const handleRoleSelectChange = (roleId: string) => {
    const role = roles.find(r => r.id === roleId);
    setSelectedRoleType(role?.role_type || '');
    if (role?.role_type === 'GLOBAL') {
      assignForm.setFieldValue('scenario_id', undefined);
    }
  };

  const columns = [
    { title: '用户ID', dataIndex: 'user_id', key: 'user_id', render: (text: string) => text || '-' },
    { title: '用户名', dataIndex: 'username', key: 'username', render: (text: string) => text || '-' },
    { title: '姓名', dataIndex: 'display_name', key: 'display_name', render: (text: string) => text || '-' },
    {
      title: '角色',
      dataIndex: 'role',
      key: 'role',
      render: (role: string) => {
        const colorMap: Record<string, string> = {
          SYSTEM_ADMIN: 'red',
          SCENARIO_ADMIN: 'blue',
          ANNOTATOR: 'green',
          AUDITOR: 'orange',
        };
        const labelMap: Record<string, string> = {
          SYSTEM_ADMIN: '系统管理员',
          SCENARIO_ADMIN: '场景管理员',
          ANNOTATOR: '标注员',
          AUDITOR: '审计员',
        };
        return <Tag color={colorMap[role] || 'default'}>{labelMap[role] || role}</Tag>;
      },
    },
    {
      title: '状态',
      dataIndex: 'is_active',
      key: 'is_active',
      render: (active: boolean, record: User) => (
        <Switch
          checked={active}
          onChange={(checked) => handleStatusChange(record.id, checked)}
          checkedChildren="启用"
          unCheckedChildren="禁用"
          disabled={record.user_id === localStorage.getItem('user_id')}
        />
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'created_at',
      key: 'created_at',
      render: (d: string) => dayjs(d).format('YYYY-MM-DD HH:mm'),
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: User) => (
        <Space>
          <Button size="small" icon={<TeamOutlined />} onClick={() => openAssignRoleModal(record)}>
            分配角色
          </Button>
          <Button size="small" icon={<EyeOutlined />} onClick={() => openRolesDrawer(record)}>
            查看角色
          </Button>
          <Popconfirm
            title="确定删除用户吗?"
            onConfirm={() => handleDelete(record.id)}
            disabled={record.user_id === localStorage.getItem('user_id')}
          >
            <Button
              size="small"
              danger
              icon={<DeleteOutlined />}
              disabled={record.user_id === localStorage.getItem('user_id')}
            />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <div style={{ marginBottom: 16 }}>
        <h2>用户管理</h2>
        <p style={{ color: '#666' }}>SSO 用户首次登录后自动创建，在此管理角色和权限。</p>
      </div>

      <Table dataSource={users} columns={columns} rowKey="id" loading={loading} scroll={{ x: 1000 }} />

      <Modal
        title={`为用户 ${selectedUser?.user_id} 分配角色`}
        open={assignRoleModalOpen}
        onCancel={() => setAssignRoleModalOpen(false)}
        footer={null}
      >
        <Form form={assignForm} onFinish={handleAssignRole} layout="vertical">
          <Form.Item name="role_id" label="选择角色" rules={[{ required: true, message: '请选择角色' }]}>
            <Select placeholder="请选择角色" onChange={handleRoleSelectChange}>
              {roles.map((r) => (
                <Select.Option key={r.id} value={r.id}>
                  {r.role_name} ({r.role_code}) <Tag color={r.role_type === 'GLOBAL' ? 'blue' : 'green'}>{r.role_type === 'GLOBAL' ? '全局' : '场景'}</Tag>
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          {selectedRoleType === 'SCENARIO' && (
            <Form.Item name="scenario_id" label="选择场景" rules={[{ required: true, message: '请选择场景' }]}>
              <Select placeholder="请选择场景">
                {scenarios.map((s) => (
                  <Select.Option key={s.app_id} value={s.app_id}>
                    {s.app_name} ({s.app_id})
                  </Select.Option>
                ))}
              </Select>
            </Form.Item>
          )}
          <Form.Item>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <Button onClick={() => setAssignRoleModalOpen(false)}>取消</Button>
              <Button type="primary" htmlType="submit">分配</Button>
            </div>
          </Form.Item>
        </Form>
      </Modal>

      <Drawer
        title={`用户角色列表 - ${selectedUser?.user_id}`}
        placement="right"
        width={600}
        open={rolesDrawerOpen}
        onClose={() => setRolesDrawerOpen(false)}
      >
        {userRoleAssignments.length === 0 ? (
          <p>该用户还没有分配任何角色</p>
        ) : (
          <Space direction="vertical" style={{ width: '100%' }} size="middle">
            {userRoleAssignments.map((assignment) => (
              <Card
                key={assignment.id}
                size="small"
                title={
                  <Space>
                    <TeamOutlined />
                    {assignment.role_name}
                    <Tag color={assignment.role_type === 'GLOBAL' ? 'blue' : 'green'}>
                      {assignment.role_type === 'GLOBAL' ? '全局' : '场景'}
                    </Tag>
                  </Space>
                }
                extra={
                  <Popconfirm
                    title="确定移除该角色吗?"
                    onConfirm={() => handleRemoveRole(selectedUser!.id, assignment.id)}
                  >
                    <Button size="small" danger>移除</Button>
                  </Popconfirm>
                }
              >
                <p><strong>角色编码:</strong> {assignment.role_code}</p>
                {assignment.scenario_id && (
                  <p><strong>场景ID:</strong> {assignment.scenario_id}</p>
                )}
                <p><strong>分配时间:</strong> {dayjs(assignment.created_at).format('YYYY-MM-DD HH:mm')}</p>
              </Card>
            ))}
          </Space>
        )}
      </Drawer>
    </div>
  );
};

export default UsersPage;

// frontend-vue/src/views/UsersPage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { usersApi, userRolesApi, rolesApi, scenariosApi, getErrorMessage } from '../api'
import type { User, Role, ScenarioApp, UserRoleAssignment } from '../types'
import { ElMessage, ElMessageBox } from 'element-plus'
import dayjs from 'dayjs'

const users = ref<User[]>([])
const roles = ref<Role[]>([])
const scenarios = ref<ScenarioApp[]>([])
const loading = ref(false)
const assignModalOpen = ref(false)
const rolesDrawerOpen = ref(false)
const selectedUser = ref<User | null>(null)
const userRoleAssignments = ref<UserRoleAssignment[]>([])
const selectedRoleType = ref('')

const assignForm = ref({ role_id: '', scenario_id: '' })

async function fetchUsers() {
  loading.value = true
  try { users.value = (await usersApi.list()).data }
  catch (e: any) { ElMessage.error(getErrorMessage(e, '获取用户列表失败')) }
  finally { loading.value = false }
}
async function fetchRoles() {
  try { roles.value = (await rolesApi.list()).data } catch { /* ignore */ }
}
async function fetchScenarios() {
  try { scenarios.value = (await scenariosApi.getAll()).data } catch { /* ignore */ }
}

async function handleStatusChange(row: User, val: boolean) {
  try { await usersApi.updateStatus(row.id, val); ElMessage.success('状态已更新'); fetchUsers() }
  catch (e: any) { ElMessage.error(getErrorMessage(e, '更新失败')) }
}

async function handleDelete(row: User) {
  try {
    await ElMessageBox.confirm('确定删除用户吗?', '确认')
    await usersApi.delete(row.id); ElMessage.success('用户已删除'); fetchUsers()
  } catch (e: any) { if (e !== 'cancel') ElMessage.error(getErrorMessage(e, '删除失败')) }
}

function openAssignModal(user: User) {
  selectedUser.value = user
  selectedRoleType.value = ''
  assignForm.value = { role_id: '', scenario_id: '' }
  assignModalOpen.value = true
}

function handleRoleSelectChange(roleId: string) {
  const role = roles.value.find(r => r.id === roleId)
  selectedRoleType.value = role?.role_type || ''
  if (role?.role_type === 'GLOBAL') assignForm.value.scenario_id = ''
}

async function handleAssignRole() {
  if (!selectedUser.value || !assignForm.value.role_id) return
  try {
    const data: any = { role_id: assignForm.value.role_id }
    if (assignForm.value.scenario_id) data.scenario_id = assignForm.value.scenario_id
    await userRolesApi.assignRole(selectedUser.value.id, data)
    ElMessage.success('角色分配成功'); assignModalOpen.value = false; fetchUsers()
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '分配失败')) }
}

async function openRolesDrawer(user: User) {
  selectedUser.value = user
  try {
    userRoleAssignments.value = (await userRolesApi.getUserRoles(user.id)).data
    rolesDrawerOpen.value = true
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '获取用户角色失败')) }
}

async function handleRemoveRole(assignmentId: string) {
  if (!selectedUser.value) return
  try {
    await userRolesApi.removeRole(selectedUser.value.id, assignmentId)
    ElMessage.success('角色已移除')
    userRoleAssignments.value = (await userRolesApi.getUserRoles(selectedUser.value.id)).data
  } catch (e: any) { ElMessage.error(getErrorMessage(e, '移除失败')) }
}

// PLACEHOLDER_MORE
const isSelf = (row: User) => row.user_id === localStorage.getItem('user_id')
const roleColorMap: Record<string, string> = { SYSTEM_ADMIN: 'danger', SCENARIO_ADMIN: '', ANNOTATOR: 'success', AUDITOR: 'warning' }
const roleLabelMap: Record<string, string> = { SYSTEM_ADMIN: '系统管理员', SCENARIO_ADMIN: '场景管理员', ANNOTATOR: '标注员', AUDITOR: '审计员' }
function formatTime(t: string) { return dayjs(t).format('YYYY-MM-DD HH:mm') }

onMounted(() => { fetchUsers(); fetchRoles(); fetchScenarios() })
</script>

<template>
  <div style="padding: 24px">
    <div style="margin-bottom: 16px">
      <h2 style="margin: 0">用户管理</h2>
      <p style="color: #666; margin: 4px 0 0">SSO 用户首次登录后自动创建，在此管理角色和权限。</p>
    </div>

    <el-table :data="users" v-loading="loading" row-key="id" style="width: 100%">
      <el-table-column prop="user_id" label="用户ID" width="150">
        <template #default="{ row }">{{ row.user_id || '-' }}</template>
      </el-table-column>
      <el-table-column prop="username" label="用户名" width="120">
        <template #default="{ row }">{{ row.username || '-' }}</template>
      </el-table-column>
      <el-table-column prop="display_name" label="姓名" width="120">
        <template #default="{ row }">{{ row.display_name || '-' }}</template>
      </el-table-column>
      <el-table-column prop="role" label="角色" width="130">
        <template #default="{ row }">
          <el-tag :type="roleColorMap[row.role] || 'info'" size="small">{{ roleLabelMap[row.role] || row.role }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="is_active" label="状态" width="100">
        <template #default="{ row }">
          <el-switch v-model="row.is_active" :disabled="isSelf(row)" active-text="启用" inactive-text="禁用" @change="(v: boolean) => handleStatusChange(row, v)" />
        </template>
      </el-table-column>
      <el-table-column prop="created_at" label="创建时间" width="160" :formatter="(_r: any, _c: any, v: string) => formatTime(v)" />
      <el-table-column label="操作" min-width="260" fixed="right">
        <template #default="{ row }">
          <el-button size="small" @click="openAssignModal(row)"><el-icon><UserFilled /></el-icon>分配角色</el-button>
          <el-button size="small" @click="openRolesDrawer(row)"><el-icon><View /></el-icon>查看角色</el-button>
          <el-button size="small" type="danger" :disabled="isSelf(row)" @click="handleDelete(row)"><el-icon><Delete /></el-icon></el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- Assign Role Modal -->
    <el-dialog v-model="assignModalOpen" :title="`为用户 ${selectedUser?.user_id} 分配角色`" width="500px">
      <el-form label-position="top">
        <el-form-item label="选择角色" required>
          <el-select v-model="assignForm.role_id" placeholder="请选择角色" style="width: 100%" @change="handleRoleSelectChange">
            <el-option v-for="r in roles" :key="r.id" :value="r.id" :label="`${r.role_name} (${r.role_code})`">
              <span>{{ r.role_name }} ({{ r.role_code }})</span>
              <el-tag :type="r.role_type === 'GLOBAL' ? '' : 'success'" size="small" style="margin-left: 8px">{{ r.role_type === 'GLOBAL' ? '全局' : '场景' }}</el-tag>
            </el-option>
          </el-select>
        </el-form-item>
        <el-form-item v-if="selectedRoleType === 'SCENARIO'" label="选择场景" required>
          <el-select v-model="assignForm.scenario_id" placeholder="请选择场景" style="width: 100%">
            <el-option v-for="s in scenarios" :key="s.app_id" :value="s.app_id" :label="`${s.app_name} (${s.app_id})`" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="assignModalOpen = false">取消</el-button>
        <el-button type="primary" @click="handleAssignRole">分配</el-button>
      </template>
    </el-dialog>

    <!-- Roles Drawer -->
    <el-drawer v-model="rolesDrawerOpen" :title="`用户角色列表 - ${selectedUser?.user_id}`" direction="rtl" size="600px">
      <p v-if="userRoleAssignments.length === 0">该用户还没有分配任何角色</p>
      <div v-else style="display: flex; flex-direction: column; gap: 12px">
        <el-card v-for="a in userRoleAssignments" :key="a.id" shadow="never">
          <template #header>
            <div style="display: flex; justify-content: space-between; align-items: center">
              <span>
                <el-icon><UserFilled /></el-icon> {{ a.role_name }}
                <el-tag :type="a.role_type === 'GLOBAL' ? '' : 'success'" size="small" style="margin-left: 8px">{{ a.role_type === 'GLOBAL' ? '全局' : '场景' }}</el-tag>
              </span>
              <el-popconfirm title="确定移除该角色吗?" @confirm="handleRemoveRole(a.id)">
                <template #reference><el-button size="small" type="danger">移除</el-button></template>
              </el-popconfirm>
            </div>
          </template>
          <p><strong>角色编码:</strong> {{ a.role_code }}</p>
          <p v-if="a.scenario_id"><strong>场景ID:</strong> {{ a.scenario_id }}</p>
          <p><strong>分配时间:</strong> {{ formatTime(a.created_at) }}</p>
        </el-card>
      </div>
    </el-drawer>
  </div>
</template>
